server:
  port: 8080
  base_url: "http://localhost:8080" 

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres" 
  name: "shotlink"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

redis:
  host: "redis"
  port: 6379
  timeout: "5s"

log:
  level: "debug"
  json: false

migrations:
  dir: "./migrations/postgres"